#!/usr/bin/env bash
# One-command test runner for the Dev Container Features in this repo.
#
# Builds each feature in a throwaway container and runs its test/<feature>/test.sh assertions.
# No publishing and no <ORG> registry needed - everything runs against local source.
#
# Requirements (already provided by this repo's dev container):
#   - Docker            -> via the docker-in-docker feature in .devcontainer/devcontainer.json
#   - @devcontainers/cli -> installed by the postCreateCommand
#
# Usage:
#   ./test/test.sh             # test everything
#   ./test/test.sh btp-cli-tools  # test a single feature (btp-cli-tools | cap-dev-stack | fiori-dev-stack)
set -e

cd "$(dirname "$0")/.."

BASE_IMAGE="mcr.microsoft.com/devcontainers/base:debian"

# The devcontainer CLI expects features at <project-folder>/src/<feature>.
PROJ=$(mktemp -d)
ln -s "$(pwd)/src" "$PROJ/src"
ln -s "$(pwd)/test"         "$PROJ/test"
trap 'rm -rf "$PROJ"' EXIT

if ! command -v devcontainer >/dev/null 2>&1; then
	echo "==> Installing @devcontainers/cli ..."
	npm install -g @devcontainers/cli
fi

if ! docker info >/dev/null 2>&1; then
	echo "ERROR: Docker is not reachable. Rebuild this dev container so docker-in-docker is active" >&2
	echo "       (Command Palette -> 'Dev Containers: Rebuild Container')." >&2
	exit 1
fi

run_single() {
	local feature="$1"
	# All features use scenario-based tests (scenarios.json).
	devcontainer features test --project-folder "$PROJ" --skip-autogenerated --features "$feature"
}

if [ -n "$1" ]; then
	echo "==> Testing feature: $1"
	run_single "$1"
	echo "==> Done ✓"
	exit 0
fi

echo "==> Testing btp-cli-tools (scenarios)"
devcontainer features test \
	--project-folder "$PROJ" \
	--skip-autogenerated \
	--features btp-cli-tools

echo "==> Testing cap-dev-stack (scenario with Node.js)"
devcontainer features test \
	--project-folder "$PROJ" \
	--skip-autogenerated \
	--features cap-dev-stack

echo "==> Testing fiori-dev-stack (scenario with Node.js)"
devcontainer features test \
	--project-folder "$PROJ" \
	--skip-autogenerated \
	--features fiori-dev-stack

echo "==> Testing npm-feeds (scenario with Node.js)"
devcontainer features test \
	--project-folder "$PROJ" \
	--skip-autogenerated \
	--features npm-feeds

echo "==> Testing dev-defaults (smoke test)"
devcontainer features test \
        --project-folder "$PROJ" \
        --skip-autogenerated \
        --features dev-defaults

echo "==> Testing typescript (scenario with Node.js)"
devcontainer features test \
        --project-folder "$PROJ" \
        --skip-autogenerated \
        --features typescript

