#!/bin/bash
# Scenario test for 'fiori-dev-stack'.
#
# This feature requires Node.js / npm, so it is exercised via a scenario that
# installs the official Node.js feature first. Run with:
#
#   devcontainer features test -p . -f fiori-dev-stack --skip-autogenerated
#
set -e

source dev-container-features-test-lib

check "yo is installed" yo --version
check "generator-fiori is installed" bash -c "npm ls -g @sap/generator-fiori"

reportResults
