#!/bin/bash
# Scenario test for 'cap-dev-stack'.
#
# This feature requires Node.js / npm, so it is exercised via a scenario that
# installs the official Node.js feature first. Run with:
#
#   devcontainer features test -p . -f cap-dev-stack --skip-autogenerated
#
set -e

source dev-container-features-test-lib

check "cds-dk is installed" cds --version
check "mbt is installed" mbt --version
check "mta is installed" mta --version

reportResults
