#!/bin/bash
# Scenario test for 'devcontainer-tools'.
#
# This feature requires Node.js / npm, so it is exercised via a scenario that
# installs the official Node.js feature first. Run with:
#
#   devcontainer features test -p . -f devcontainer-tools --skip-autogenerated
#
set -e

source dev-container-features-test-lib

check "devcontainer CLI is installed" devcontainer --version

reportResults
